name: Benei Aor USA
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1450253
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Benei Aor USa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f5faf6'
    - '#f60d09'
    - '#7479d5'
    - '#ede40d'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
